### ISSUE TITLE
Stratum Feedback

### ISSUE THREAD

**Issue by tripflex** [xelpool/Xatum#1]
Thanks for putting all this together!  A few questions and some feedback around the protocol definition.

1.) Is there a reason for creating an entirely new "xatum" protocol and not just using standard protocol with adjustments to the arguments?  For example `mining.authorize` etc basically using JSONRPC?  This may make it much more difficult for other miners to integrate having to build out a completely custom protocol instead of just using protocol they are already used to, with a few minor changes to arguments and how they are passed.

2.) On the submit, should we not just have the miner submit the timestamp and nonce and then pool side we can construct the PoW hash?

3.) You have "success" packet sent when a share is submitted, i think we should follow other normal standards here and return a specific error response instead of including the error in the `msg` response?

4.) I love the `print` idea, that would be great for sending some kind of message to the miner from pool side.

5.) In regards to the ping/pong handling, IMO this should be the other way around.  Server -> Client instead of Client -> Server.  Miners already measure latency based on other communication calls so no need to add additional handling for this, and majority of the time seeing if connection should be kept open would be determined by the server and not the client.  The server would send a ping to client to see if it's still alive, not the other way around.

**Comment by duggavo** [comment]
Hello, thank you for taking time to review the protocol!
1.) "Standard" protocols like Cryptonote/XMRIG-style Stratum are considerably more complex - I don't like the idea of depending on old, less efficient and more complex protocols.
2.) That's a great idea. I'll consider adding this before the Xatum public release
3.) Can you explain, do you mean using one single packet instead of two different kind of packets? Does that really make difference?
5.) That's a good idea too.


Thank you for your valuable feedback!

**Comment by duggavo** [comment]
@tripflex I've implemented the pong/pong handling that you suggested, but I decided to keep the "submit" as-is, for the following reasons:
- Header hash is required because it acts as a kind of "job id"
- Extra nonce can be used in the future to allow proxies (in a similar way to xmrig-proxy's Nicehash mode) to modify the last N bytes of it and merge the connections of many miners
- The PoW hash is submit for "light verification" - since the Xelis hash function is very slow, not all of the shares' PoW hashes are checked for "trusted" miners, which mean miners that have a long history of good shares (which is what most Cryptonote pools already do)
- The public key is not required (32 bytes saved)

Implementing that change would save 32 bytes (~43 bytes with base64 encoding), but I don't think that would be worth the effort, especially for mining software developers, which would have to implement the conversion from BlockMiner to another binary structure before encoding everything to base64.

**Comment by duggavo** [comment]
Closed by commit 75c87e0da40387d7cf77bf0e48076739a403c1e8
